import BootstrapProvider from '@bootstrap-styled/provider/lib/BootstrapProvider';
import Col from '../src/Col';
import FaStacked from '../src/Fa/FaStacked';
import Label from '../src/Label';
import Option from '../src/Option';
import Output from '../src/Output';
import Section from '../src/Section';
import TetherContent from '../src/TetherContent';
global.BootstrapProvider = BootstrapProvider;
global.Col = Col;
global.FaStacked = FaStacked;
global.Label = Label;
global.Option = Option;
global.Output = Output;
global.Section = Section;
global.TetherContent = TetherContent;
